version: '3'

services:
  web:
    image: 011837373437.dkr.ecr.us-east-1.amazonaws.com/test-repository:simplewebapp
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.worker == true